name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup BATS testing framework
      uses: mig4/setup-bats@v1.0.1
    - run: bats ./test-install.sh
      
    - name: Notify status to slack
      uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        author_name: My Env Installer
        icon_emoji: ':santa:'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
      
